### PR TITLE
rose bush: jobs: cylc-suite.db task_job_logs table

### LINKED ISSUE #1646: rose bush: take advantage of new tables in cylc suite run time database file
cylc/cylc#1493 and cylc/cylc#1503 introduce 3 new tables to the cylc suite run time database:
* `broadcasts` (see also cylc/cylc#1519)
* `task_jobs`
* `task_job_logs`

Rose Bush should take advantage of them:

* Display current and historical broadcasts in a table. (New page?)
* `task_jobs` should be much easier to query than `task_events`.
  * We should be able to write simpler SQL to get a job listing.
  * We should now be able to easily query timing information (#1308).
* `task_job_logs` will replace the `log_files` table in `log/rose-job-logs.db`.
  This table should be consulted first if it exists.
  We should only need to consult the `log_files` table in `log/rose-job-logs.db`
  to see if the file is in a *tar* archive or is removed.

We should probably have a listing of tasks, with their jobs grouped together.
* Job exit status does not always correspond to the task state.
* Some tasks may have no jobs! (See cylc/cylc#1494 for example.)

### PR DESCRIPTION
**Pull request by matthewrmshin**
Rose Bush jobs view can now use the `task_job_logs` table in
`cylc-suite.db`.

Close #1646.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
@kaday @arjclark please review.

**Comment by kaday** [comment]
Code looks good, how it is best to test this @matthewrmshin ?

**Comment by matthewrmshin** [comment]
To test: run a suite at cylc-6.7.1. Switch off all event handlers running `rose suite-hook`. Rose Bush jobs list would be unable to show job logs files on master, but should work with this branch.

**Comment by matthewrmshin** [comment]
(After this is merged, I am going to give #1010 a crack - at least on the data layer if not on the presentation layer.)

**Comment by kaday** [comment]
It is fixed in my environment. Over to @arjclark for review 2

**Comment by matthewrmshin** [comment]
Branch re-based.

**Comment by arjclark** [comment]
@matthewrmshin - there're now conflicts on this branch - I suspect as a result of my change in rose bunch.

**Comment by matthewrmshin** [comment]
Branch re-based again.

**Comment by arjclark** [comment]
@matthewrmshin - getting a mysterious "ghost" cycle on one of my older suites for a cycle that hasn't run yet on the cycles list page - displays cycle as being there with 0 run. (see mot-ab182 in my space). Is this intentional? I suspect its a result of the presence of clock triggered tasks for the future cycle existing in the task_states table with the waiting status.

**Comment by arjclark** [comment]
Also getting traceback on running "rose bush stop", though I don't think that's due to this branch:
```
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/net/home/h06/aclark/rose.git/lib/python/rose/bush.py", line 537, in <module>
    ws_cli(RoseBushService)
  File "/net/home/h06/aclark/rose.git/lib/python/rose/ws.py", line 78, in ws_cli
    status = _get_server_status(service_cls)
  File "/net/home/h06/aclark/rose.git/lib/python/rose/ws.py", line 165, in _get_server_status
    LOG_ROOT_TMPL % (service_cls.NS, service_cls.UTIL)) + ".status"
TypeError: format requires a mapping
```

**Comment by arjclark** [comment]
^ Above traceback seems to be a result of this change: https://github.com/metomi/rose/commit/d673ee5950dd4751177d7b316c6cad0c13499745#diff-7cf30be100b805a1060f5599973085f7R36 rather than anything in this branch.

**Comment by matthewrmshin** [comment]
I think both issues are on master, and not a result of the change in this branch.

**Comment by matthewrmshin** [comment]
`rose bush stop` CLI should now be fixed.

**Comment by arjclark** [comment]
> I think both issues are on master, and not a result of the change in this branch.

Confirmed.

> `rose bush stop` CLI should now be fixed.

Tested as now working.

**Comment by arjclark** [comment]
Test battery passing. Looks ok to me.

**Pull request merged**
