### PR TITLE
rose bush: page navigation always visable bottom

### LINKED ISSUE #1609: rose bush: cycles list add page no. info to bottom of page
`Page w of x ~ Entries 1-yy of zzz` to be displayed at the bottom as well as the top of the `rose bush` page.

### PR DESCRIPTION
**Pull request by kaday**
Closes #1609

### CODE REVIEW

**Comment by kaday** [comment]
@arjclark please review

**Comment by arjclark** [comment]
As discussed, can we have a background for the div. Looks good to me but will run it past one of the others just to make sure.

**Comment by kaday** [comment]
@arjclark please review, @matthewrmshin is happy with it. After a discussion we agree that we would like to update it once we are using Bootstrap3.

**Comment by arjclark** [comment]
Looks good to me, useful to be able to scroll through this way. Tested as working in my environment, no problems or slowdown encountered and none expected.

**Pull request merged**
