### PR TITLE
rose doc: Updated to include value

### PR DESCRIPTION
**Pull request by kaday**
Noticed that this was missing from the doc

### CODE REVIEW

**Comment by kaday** [comment]
@dpmatthews please review the doc as discussed or reassign

**Comment by kaday** [comment]
@arjclark please review this minor doc change as Dave is unavailable. Thanks.

**Comment by arjclark** [comment]
Looks fine to me.

**Comment by benfitzpatrick** [comment]
There is a problem here - it says 'value' in places instead of 'values', and 'values' is already covered in the Metadata Tutorial (which is why it's titled 'More Metadata Options' - following on from there).

**Comment by arjclark** [comment]
"value" corrected to "values" in #1724.

**Pull request merged**
