### PR TITLE
rose host-select: reinstate timeout and improve random selection logic

### PR DESCRIPTION
**Pull request by matthewrmshin**
Reinstate timeout logic. Kill SSH commands if they take too long to complete - treat hosts with killed SSH commands as dead hosts.

Run SSH commands in serial (to reduce system load) when selecting by random with no thresholds.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
@benfitzpatrick please review.

**Comment by arjclark** [comment]
@matthewrmshin - now these're done in serial, does this present a problem for interaction under cylc host select and hitting the timeout there? e.g. test host 1, reject it, test host 2, takes a while, reject it, test host 3, cylc host selection treated as failed.

**Comment by matthewrmshin** [comment]
> now these're done in serial, does this present a problem for interaction under cylc host select and hitting the timeout there? e.g. test host 1, reject it, test host 2, takes a while, reject it, test host 3, cylc host selection treated as failed.

No, because we don't use random for that, so it will continue to run in parallel.

**Comment by benfitzpatrick** [comment]
Can we have a test for it?

**Comment by matthewrmshin** [comment]
(Just discovered that the 01 test was there to test time out. I have updated the logic to do it again.)

**Pull request merged**
