### PR TITLE
rose app-upgrade: fix trigger conflict with namelist prettification

### PR DESCRIPTION
**Pull request by benfitzpatrick**
`trigger` state-fixing is run immediately after an app configuration is upgraded within `rose app-upgrade`. After the app is upgraded, the configuration object is dumped and prettified
to e.g. compress namelist syntax (e.g. `0,0,0,0,0,0` -> `6*0`).

This prettification is done in-place in current master, so the configuration object itself is
returned with these modifications. In the `trigger` state-fixing, this object is used and it can
lead to incorrect triggering based on these values. Further runs with `rose macro` or `rose edit`
will correctly fix these problems. 

This bug does not affect `rose edit`, which uses a different dump mechanism (and does it at different times).

The new test fails current master, passes on this branch.

### CODE REVIEW

**Comment by arjclark** [comment]
Looks ok to me. No problems from the test battery.

@scwhitehouse - can you confirm this fixes your reported problem?

**Comment by scwhitehouse** [comment]
That seems to stop the gratuitous triggering. Should running rose app-upgrade also include the effects of rose macro --fix, as that doesn't seem to be included?

**Comment by benfitzpatrick** [comment]
There shouldn't be anything to fix if the app validates before the upgrade and the upgrade macros are doing their job... any subsequent metadata errors are a clear sign of fault with the upgrade macros (missing out compulsory variables, adding things with the wrong type).

**Comment by scwhitehouse** [comment]
Ok, looks like there is something missing from this users macro, so I'm happy with this.

**Pull request merged**
