### PR TITLE
Rose user guide rose stem

### PR DESCRIPTION
**Pull request by oliver-sanders**
**Built on #2170, merge after**

Migrate the rose stem user guide into the new rose documentation. Some documentation moved into the codebase, otherwise a direct translation.

### CODE REVIEW

**Comment by stevewardle** [comment]
It all looks fine to me, with the exception of the docstring at the top of `grepper.py`... Although perhaps I'm just unfamiliar with the markdown syntax... it says `rose_ana[ana:ANALYSIS_CLASS]'` - I assume that translates to the `[rose_ana]` section of a user `rose.conf` file?  The example of using this in the rest of the documentation is correct I just can't see how this comment relates to it...  Likewise the rest of that sentence/paragraph reads a little oddly... the 3 places it can go are:

- In the `[rose_ana]` section of the site configuration
- In the `[rose_ana]` section of a user's personal `rose.conf`
- In the `[ana:config]` section of a `rose_ana` app

**Comment by oliver-sanders** [comment]
Hows this?

> I assume that translates to the `[rose_ana]` section of a user `rose.conf` file?

It translates to the `[rose-ana]` section in the `rose.conf` file, is this meant to be `[rose_ana]`?

**Comment by oliver-sanders** [comment]
Is `[ana:config]` different to `[ana:ANALYSIS_CLASS]`?

**Comment by stevewardle** [comment]
I would say so... the sections in the `rose_ana` files are based on the name of the class they are meant to call (I guess that might be where "Analysis Clask" in that comes from) but the section that can contain the "global" settings must be called `[ana:config]`

**Pull request merged**
