### PR TITLE
Unify init logic for rose-bush and rosie-ws

### PR DESCRIPTION
**Pull request by matthewrmshin**
Unify web service start up logic under a single module `rose.ws`.
* Modify `rosa ws` CLI to be the same as `rose bush`, i.e. `rosa ws start` to start ad hoc server.
* Reviewers should concentrate on the change of this logic.

Fix mod_wsgi + cherrypy Apache error 200 problem.
* Advice from http://docs.cherrypy.org/en/latest/deploy.html#wsgi-servers

Rosie Web Service is re-branded *Rosie Discovery Service*.

Improve layout of HTML technology library.
* `lib/html/static/` for static contents, e.g. CSS, images, JavaScript, etc.
* `lib/html/template/` for HTML-Jinja2 templates.
* Large number of changes mainly associated with reorganisation and renames.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
@benfitzpatrick @arjclark please review.

**Comment by benfitzpatrick** [comment]
I don't think the rebranding should leave out the actual `rosa ws` command. It makes much more sense to go for `rosie disco start` when we have `rose bush start`.

`Rosie Web` is the title of the web pages - I guess this can now have 'Discovery' in the title.

Otherwise looks fine, tests as working.

**Comment by matthewrmshin** [comment]
@benfitzpatrick the rebrand should now be a bit more complete.

**Comment by matthewrmshin** [comment]
Rebranded tests.

**Comment by benfitzpatrick** [comment]
Looks fine. Tests are a bit off at the moment, probably due to system issues.

**Comment by arjclark** [comment]
Looks ok to me. @matthewrmshin - did you maybe want to put a deprecation warning (or something to that effect) in rosa-ws?

Happy for merge on commenting.

**Comment by matthewrmshin** [comment]
> did you maybe want to put a deprecation warning (or something to that effect) in rosa-ws?

It is in its documentation. Do you want it to be a run time thing?

**Comment by arjclark** [comment]
Yeah, I was thinking a runtime warning.

**Comment by arjclark** [comment]
Following discussion agreed not worth the extra work.

**Pull request merged**
