### PR TITLE
rose bush: unify HTTP 403 or 404 returns

### LINKED ISSUE #1093: rose bush: catch permission denied
Rose Bush should catch any file system permission denied error, and return a 403 (instead of dying with 500).

### PR DESCRIPTION
**Pull request by matthewrmshin**
Close #1093.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
@arjclark please review.

**Comment by arjclark** [comment]
@matthewrmshin  - looks good to me. Any way for me to test this is working correctly?

**Comment by arjclark** [comment]
Manually tested as discussed and now correctly erroring.

**Comment by arjclark** [comment]
Tested as working in my environment. Test battery unaffected.

**Pull request merged**
