### PR TITLE
doc: upgrade cylc-sphinx-extensions version

### PR DESCRIPTION
**Pull request by oliver-sanders**
Minor tweaks to adapt to:

* Higher cylc-sphinx-extensions version.
* Higher hieroglyph version.
* Higher sphinx version.

### CODE REVIEW

**Review by wxtim — APPROVED** [review]
- [x] Looks reasonable.
- [x] Allows the automated document build to get a bit further before failing.
- [ ] Documentation build works.

I suspect that given the current state of this repository I'm happy merging if this is as succeeded as you expect it to be.

**Comment by oliver-sanders** [comment]
That should fix the linkcheck errors that were causing the build to fail.

**Comment by wxtim** [comment]
I'm afraid that it's now failing in the same way as the branch I tried fixing. Sorry.

**Comment by oliver-sanders** [comment]
Just one more broken link to fix...

**Comment by oliver-sanders** [comment]
BTW I updated all Python2 docs links to Python3.

A nice example of the link checker doing its job by informing us that all the Python2 links were being redirected.

**Comment by oliver-sanders** [comment]
@wxtim that did it.

**Pull request merged**
