### PR TITLE
rose bush: cycles/jobs: display suite host:port

### PR DESCRIPTION
**Pull request by matthewrmshin**
Take advantage of cylc/cylc#1705

### CODE REVIEW

**Comment by matthewrmshin** [comment]
@arjclark @kaday please review. New test requires cylc/cylc#1705 or it will skip.

**Comment by arjclark** [comment]
I'm inclined to wait until cylc/cylc#1705 is finalised and merged before pressing go on this one in case anything changes once @hjoliver has had chance to review it properly.

**Comment by arjclark** [comment]
As a first pass, looks ok and test battery works in my environment.

I'm not so sure how helpful the line:

Suite has failed tasks \, is running \, last activity 25 minutes ago

is in one of my older suites as, yes a task failed some time ago (last month), but it was subsequently suicided out and has no bearing on the current state of the suite. This has the potential to end up worrying users needlessly...

**Comment by matthewrmshin** [comment]
> Suite has failed tasks , is running , last activity 25 minutes ago

This line has always been there, but was placed in the navigation bar at the top right.

I have moved it down so we can add the `host:port` information in as well. (Otherwise, the navigation bar will look too busy.)

**Comment by arjclark** [comment]
> This line has always been there, but was placed in the navigation bar at the top right.

Got to say, even with those directions I've just struggled to find the equivalent in the old view (2015.12.0) - admittedly obvious once I found it though that that was what has moved down. It is definitely more prominent now for better or worse. IMHO I don't like that being there where it's now the first thing you see but I'm happy for the rest of the team to decide what they think and overrule me on this one - @metomi/metos please take a look and see what you think. (N.B. I have no objection to the "last activity" part of the entry being there, so if this were a case of the icons being kept where they were and the leading line being something like "running on <hostname>, last activity <offset> ago" I wouldn't have any objection).

**Comment by arjclark** [comment]
(Sorry, above should've been @metomi/owners)

**Comment by matthewrmshin** [comment]
Branch re-based.

**Comment by kaday** [comment]
Passes tests in my environment.
Looks okay to me.
I am happy with the change.

**Pull request merged**
