### PR TITLE
Config iterator fix

### LINKED ISSUE #1821: rose.config.ConfigNode: fix __iter__ method
The `__iter__` method in `rose.config.ConfigNode` currently does not work - for example:
```python
import rose.config
a = rose.config.ConfigNode()
for item in a:
    print a
```
fails with:
```
TypeError: __iter__() takes exactly 2 arguments (1 given)
```

### PR DESCRIPTION
**Pull request by jonseddon**
This closes #1821.
@matthewrmshin Please review
@benfitzpatrick  Please review

### CODE REVIEW

**Comment by matthewrmshin** [comment]
@jonseddon please add your name to the list of code contributors in the file `CONTRIBUTING.md`, so it can be merged with this pull request.

See https://github.com/metomi/rose/blob/master/CONTRIBUTING.md for detail.

**Comment by jonseddon** [comment]
@matthewrmshin I added my name to CONTRIBUTING.md in the branch of my fork. Should I have added it somewhere else?

**Comment by matthewrmshin** [comment]
> I added my name to CONTRIBUTING.md in the branch of my fork. Should I have added it somewhere else?

@jonseddon No, what you have done is absolutely correct.

**Comment by matthewrmshin** [comment]
Change looks good to me.

**Comment by benfitzpatrick** [comment]
Looks good to me too. Thanks!

**Pull request merged**
