### PR TITLE
rose doc: fixed bug with single page navigation

### PR DESCRIPTION
**Pull request by oliver-sanders**
Fixed a bug whereby sections could be missing from the navigation in the single page version of the documentation.

@matthewrmshin Please Review and add a second if required

### CODE REVIEW

**Comment by oliver-sanders** [comment]
Added an image URL fix (04e9ca76763cff2293ff9b243b09c4cbf5bda73e) in with this PR.

**Comment by matthewrmshin** [comment]
We have found some oddity on load. Not sure if it can be fixed or not. The change is otherwise good.

**Comment by matthewrmshin** [comment]
@arjclark please review 2.

**Comment by oliver-sanders** [comment]
@matthewrmshin @arjclark 75b35709474c7a71f1357d703d7b4537beb302b8 Fixes the bug where scrollspy selects the incorrect section or none at all from the navigation on load.

**Comment by matthewrmshin** [comment]
Looks good to go.

**Comment by arjclark** [comment]
Looks ok to me. Eyeballing review of documentation seems to be ok.

**Pull request merged**
