### PR TITLE
rose edit, rosie go: handle site/user incorrect value types

### PR DESCRIPTION
**Pull request by benfitzpatrick**
This handles errors for site or user configuration for `rosie go` and `rose edit`.

If a user had e.g.:
```
[rose-config-edit]
should-show-custom-description=false
```
then this would evaluate to the string `'false'` instead of a boolean. This kind of error can be hard to debug. This change raises an exception if the (cast) type for an override option differs from the default
value's type, unless the default value is `None`.

I've also consolidated the override functionality since it was basically the same for `rosie go` and `rose edit`.

@arjclark, @oliver-sanders please review.

### CODE REVIEW

**Comment by arjclark** [comment]
So, above example now crashes out on launch with:

Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 104, in _run_module_as_main
    loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib64/python2.6/runpy.py", line 79, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib64/python2.6/pkgutil.py", line 456, in get_loader
    return find_loader(fullname)
  File "/usr/lib64/python2.6/pkgutil.py", line 466, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib64/python2.6/pkgutil.py", line 422, in iter_importers
    __import__(pkg)
  File ".../rose.git/lib/python/rose/config_editor/__init__.py", line 761, in <module>
    load_override_config(["rose-config-edit"])
  File ".../rose.git/lib/python/rose/config_editor/__init__.py", line 757, in load_override_config
    type(orig_value), type(cast_value))
rose.config_editor.OverrideValueError: rose-config-edit=should-show-custom-description=false: site/user conf: was <type 'bool'>, supplied <type 'str'>
```
I guess I'd expected it to handle the config error gracefully i.e. flag a warning and ignore it.

**Comment by benfitzpatrick** [comment]
I'm open to doing that

**Comment by arjclark** [comment]
I think that'd be my preferred behaviour.

**Comment by benfitzpatrick** [comment]
OK, now just a warning. I've also disallowed changing any constants beginning with `_`.

**Comment by arjclark** [comment]
Looks good to me. Manually tested as working. Over to you @oliver-sanders

**Comment by benfitzpatrick** [comment]
Now found and fixed the examples in the documentation which led to the original user error.

**Comment by oliver-sanders** [comment]
Also examples in doc/rose-rug-config-edit.html?

**Comment by benfitzpatrick** [comment]
Um, isn't that what I did? I can't see any that I've missed...

**Comment by oliver-sanders** [comment]
Whoops, had checked out your other PR.

**Comment by oliver-sanders** [comment]
Looks good.

**Pull request merged**
