### PR TITLE
1849.dump suites and owners

### LINKED ISSUE #1849: rosie graph: produce list of suites and owners
It has been requested that rosie graph have the ability to produce a list of suites and owners as an output file in order to make it easier to get a list of people to contact regarding an issue from a parent suite.

Should be a relatively minor but potentially quite useful enhancement.

### PR DESCRIPTION
**Pull request by arjclark**
Closes #1849.

Adds `--print-graph` option to rosie graph command for printing rosie graph results to the command line instead of plotting them. Involves some minor rearrangement of the code to allow for this.

Documentation updated and new tests added to extend those in `t/rosie-graph/00-basic.t`

@benfitzpatrick - please review 1
@kaday - please review 2

### CODE REVIEW

**Comment by benfitzpatrick** [comment]
I think `--text` or something is more concise, and it needs pep8-ing to pass the test battery - but otherwise good to go for me.

**Comment by arjclark** [comment]
@benfitzpatrick - sorry about that, was sure I'd tested that one (never seen that particular error either). Have renamed to "--text" in lieu of any better naming ideas (can't think of anything better myself).

Over to you @kaday

**Comment by kaday** [comment]
@arjclark do you need to add a test child > 1?

**Comment by kaday** [comment]
Test battery passes if master is merged in. Please merge master.

**Comment by arjclark** [comment]
@kaday - master merged in and additional test item added in for child > 1 (unfortunately touches on the rest of the rosie-graph as a result but ultimately not a bad thing).

**Comment by kaday** [comment]
Looks good to me. Passes in my environment.

**Pull request merged**
