### PR TITLE
rosie graph: plot suite ancestry

### PR DESCRIPTION
**Pull request by benfitzpatrick**
The proliferation of suites and the copy-suite working practice can make it difficult
to keep track of which suites are related, and how. This command creates a graph
of suite ancestry.

The internals are similar to `rose metadata-graph` (but simpler).

### CODE REVIEW

**Comment by arjclark** [comment]
@benfitzpatrick - generally looks nice. However, as kind of discussed earlier, can we have a depth option for how far up/down the provenance is tracked (you may wish to have separate child and parent depths - will leave this to you but I can see it being useful when you want to know what suites have spawned from you but don't care about where you've come from).

I think there should be a default depth of 1 for whatever this setting ends up being with the option of specifying yourself via CLI options. An example of not being particularly helpful to trace the entire tree would be to run on our site for mi-ab872.

@matthewrmshin - I'm nominating you as second reviewer to make sure there are no load concerns.

**Comment by benfitzpatrick** [comment]
`--distance` option added. I've left the limit as 'unlimited', as the graph trimming can give a misleading impression if you don't know what's going on. Maybe scissor nodes like cylc would be a good addition later if we were to introduce it.

I also think that the huge graph is kind of cool...

**Comment by arjclark** [comment]
Ok. Looks good to me. Test battery passing in my environment.

Over to @matthewrmshin to review 2 and make sure there are no load implications.

**Comment by benfitzpatrick** [comment]
Anything holding this up?

**Comment by benfitzpatrick** [comment]
(I want to use it!)

**Comment by arjclark** [comment]
Awaiting review from @matthewrmshin - climate are also eager to get access to this.

**Comment by matthewrmshin** [comment]
The command does create a CPU load on the server that can last for a few seconds. Is this acceptable?

**Comment by arjclark** [comment]
@matthewrmshin - acceptable to me as it isn't going to be being run continuously. Up to you if you consider it a concern.

**Pull request merged**
