### PR TITLE
Rose Bush: file view: now recognise [DEBUG]

### LINKED ISSUE #1088: rose bush: highlight [DEBUG] prefix tag in output
We support auto-highlighting of some prefix logging tags like `[INFO]` and `[WARN]` - we should add highlighting for `[DEBUG]` as well.

### PR DESCRIPTION
**Pull request by matthewrmshin**
Close #1088. @benfitzpatrick @arjclark please review.

### CODE REVIEW

**Comment by benfitzpatrick** [comment]
Doesn't work - the `line[0:6] in PREFIXES` condition won't pass for a 7 character prefix like '[DEBUG]'

**Comment by matthewrmshin** [comment]
Branch re-based, and the logic should now work.

**Comment by benfitzpatrick** [comment]
Looks OK to me.

**Comment by arjclark** [comment]
Looks ok to me.

**Pull request merged**
