### PR TITLE
Removed un-necessary metadata refresh.

### PR DESCRIPTION
**Pull request by oliver-sanders**
Removed an un-necessary line of code introduced by #1856.

@benfitzpatrick Please Review
@matthewrmshin Please Review

### CODE REVIEW

**Comment by matthewrmshin** [comment]
Looks OK 2.

**Comment by benfitzpatrick** [comment]
I think this change stops the `-M` metadata-path command line options from working - maybe they aren't being passed in initially any more?

**Comment by oliver-sanders** [comment]
@benfitzpatrick Perhaps not so un-necessary after all.

**Comment by benfitzpatrick** [comment]
True, but it's still loading the metadata twice which isn't great. Can we find a way to do it once?

**Comment by oliver-sanders** [comment]
@benfitzpatrick Removed un-necessary refresh.

**Comment by benfitzpatrick** [comment]
Looks good. @matthewrmshin, please review 2 and merge if you like.

**Pull request merged**
