### PR TITLE
rose bush: fix fuzzy time logic for suites/cycles

### PR DESCRIPTION
**Pull request by matthewrmshin**
Display fuzzy time again by default for suites and cycles methods. (Broken by #1791.)
Add toggle delta-time button for them as well.

@arjclark @kaday please review.

### CODE REVIEW

**Comment by arjclark** [comment]
Looks good to me. Test battery passing and manual testing confirms change in behaviour. Over to you @kaday for review 2.

**Comment by kaday** [comment]
Please can you merge in master so that test battery passes.

**Comment by matthewrmshin** [comment]
Branch re-based.

**Comment by kaday** [comment]
Looks okay. Passes test battery in my environment.

**Pull request merged**
