### PR TITLE
doc: pdf output

### PR DESCRIPTION
**Pull request by oliver-sanders**
Add proper support for PDF output generated via LaTeX.

* Change the implementation of `rose_domain` to be compatible with builders other than the HTML builder.
* Fix LaTeX errors.
* Extract PDF documents and place them in a pdf/ directory.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
Travis CI failing. Missing command or some such?

**Comment by oliver-sanders** [comment]
Just getting the LaTeX dependencies sorted out, come back in a few hours!

**Comment by oliver-sanders** [comment]
Should now be good to go!

**Comment by oliver-sanders** [comment]
Confirmed that the docs build on the https://github.com/metomi/metomi-vms (Ubuntu).

**Pull request merged**
