### PR TITLE
rose.reporter: better unicode handling

### LINKED ISSUE #1916: rose.reporter, rose.fs_util: handle unicode file events
When a non-ASCII character like ⚘is present in a file name, any filesystem event referencing it from rose.fs_util (on our current system?) will cause an error like this:
```
  File "/opt/rose/lib/python/rose/app_run.py", line 330, in _prep
    self.fs_util.delete(path)
  File "/opt/rose/lib/python/rose/fs_util.py", line 101, in delete
    self.handle_event(FileSystemEvent(FileSystemEvent.DELETE, path))
  File "/opt/rose/lib/python/rose/fs_util.py", line 69, in handle_event
    return self.event_handler(*args, **kwargs)
  File "/opt/rose/lib/python/rose/reporter.py", line 176, in report
    msg = unicode(message)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 8: ordinal not in range(128)
```

### PR DESCRIPTION
**Pull request by benfitzpatrick**
This fixes #1916. It isn't that nice. It is basically a workaround for systems that allow unicode file naming but do not have a locale that supports formatting it correctly.

@matthewrmshin, @arjclark please review.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
Logic works correctly. However, I think the test is OTT (having to run `rose task-run` in a suite). A simple `rose app-run` test should do the trick. E.g.:

```cfg
[command]
default = true

[env]
FLOWER = ⚘
```

`rose app-run` in normal verbosity should print `[INFO] export FLOWER=⚘` on line 1 of STDOUT.

**Comment by arjclark** [comment]
Looks ok to me. Test battery working for me with exception of `t/rose-app-run/13-file-source-tilde.t` which also appears bust on master (confirmed separately with @benfitzpatrick), so not unique to this pull request.

Once @matthewrmshin's less aggressive test proposal is in this should be good to go in.

**Comment by benfitzpatrick** [comment]
Replaced task-run test with Matt's one.

**Comment by matthewrmshin** [comment]
Looks OK. Tests OK in my environment.

**Pull request merged**
