### PR TITLE
Fix cylc URLs in documentation. [Fail only codecov]

### PR DESCRIPTION
**Pull request by wxtim**

### CODE REVIEW

**Comment by oliver-sanders** [comment]
We now have a test failure: `./t/rosie-id/00-basic.t` (unrelated obviously).

Perhaps try rebasing?

**Comment by wxtim** [comment]
@sadielbartholomew - I seem wierdly unable to add you as a reviewer, but If you could review and merge we'd have one less PR, and I think it's a 5min jobbie.

**Comment by sadielbartholomew** [comment]
That's bizarre, @wxtim, let me know if this problem persists across Rose PRs. For now, I've added myself. Reviewing in a moment.

**Comment by sadielbartholomew** [comment]
[Two approvals, where one would be sufficient contextually, hence safe to merge. Matt on leave.]

**Pull request merged**
