### PR TITLE
bush: Only serve files from log dir + suite.rc[.processed]

### PR DESCRIPTION
**Pull request by oliver-sanders**
Solution to prevent misuse of rose bush until #2165 is merged / closed.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
At the moment there is some duplicate checking of parameters. Rather a parameter is checked twice than not checked at all. To prettify things we would need either to:

* Begin a larger refactor.
* Turn the logic on its head, checking parameters as they arrive in the exposed methods (this will probably result in some code duplication as we would need to form then reform paths).

**Comment by sadielbartholomew** [comment]
@oliver-sanders: fair enough, I agree priority-wise it is not crucial to remove duplication & I believe you if you say it is not possible to do with a few changes. I would suggest creating an issue for this but it seems relatively unimportant.

Sorry if I was holding things up with that comment, I was just awaiting a reply.

**Comment by oliver-sanders** [comment]
> I would suggest creating an issue for this but it seems relatively unimportant.

It would be nice to have a general tidy up of rose bush in general, the exposed methods are much too long and should be broken down. We might be able to add some automatic checking of arguments...

**Comment by oliver-sanders** [comment]
We now have to think about porting this to https://github.com/cylc/cylc/pull/2614

**Comment by sadielbartholomew** [comment]
Yes, perhaps once it is migrated we can go in & do the tidy up. Seems like a good time.

**Comment by sadielbartholomew** [comment]
Yes, indeed - I will add it to the checklist so I do not miss it.

**Pull request merged**
