### PR TITLE
rosie.ws_client: more retries on credential change

### LINKED ISSUE #1927: rosie go: fail on forgotten username and wrong cached password
If a user has an invalid cached Rosie service password, but does not have
a cached username, then rosie go will fail after the username prompt with:

```
ben@portraitmonitorsrule$ rosie go --prefix=u
[WARN] https://some/path/to/rosie/me/hello: {}: 401
Traceback (most recent call last):
  File "/opt/python/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/python/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/opt/rose/lib/python/rosie/browser/main.py", line 1504, in <module>
    main()
  File "/opt/rose/lib/python/rosie/browser/main.py", line 1486, in main
    raise exc
rosie.ws_client.RosieWSClientError: hello: {}
```

This set of circumstances is quite hard to achieve, because we always now cache the
username in `~/.metomi/rose.conf` and leave it there.

### PR DESCRIPTION
**Pull request by matthewrmshin**
Should fix #1927.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
Now it keeps retrying as long as the user is entering different credentials.

**Comment by matthewrmshin** [comment]
@benfitzpatrick @oliver-sanders please review and sanity check, or reassign.

**Comment by benfitzpatrick** [comment]
Looks fine.

**Comment by oliver-sanders** [comment]
Looks sane.

**Pull request merged**
