### PR TITLE
Rose stem mirror variable incorrect when run within subdirectory

### PR DESCRIPTION
**Pull request by scwhitehouse**
The `_MIRROR` variable in rose-stem isn't being set correctly when the command is invoked from within a subdirectory, it should have the base path of the URL, but it currently includes the path to the location where the command was run. This aims to fix it, and also to add a test which would have showed up the issue.

### CODE REVIEW

**Comment by scwhitehouse** [comment]
@matthewrmshin please can you take a look at this when you get a minute?

**Comment by matthewrmshin** [comment]
Looks OK 1. Tests OK. @benfitzpatrick please review 2.

**Comment by benfitzpatrick** [comment]
Looks fine, but there is a `cp` that needs removing in the test.

**Comment by scwhitehouse** [comment]
Oops, erroneous `cp` in test removed!

**Pull request merged**
