### PR TITLE
rosa svn-post-commit: decode DB strings to utf-8

### PR DESCRIPTION
**Pull request by matthewrmshin**
Only pass "utf-8" strings to discovery database.

@benfitzpatrick @kaday please review.

### CODE REVIEW

**Comment by kaday** [comment]
Passes test battery in my environment.
Looks okay to me.

**Comment by benfitzpatrick** [comment]
Looks OK, but can we have a test to see if `rosie lookup`/`ls` behaves correctly when we have this in the database? Can it search for the € sign? Can it process it out to the display without crashing?

**Comment by matthewrmshin** [comment]
Added `rosie lookup` test to display € sign.

**Comment by benfitzpatrick** [comment]
Ok, works for me

**Pull request merged**
