### PR TITLE
setup: add pygraphviz opt dep

### LINKED ISSUE #2523: `pygraphviz` dependency
Currently there is a dependency on `pygraphviz` which is not listed in `setup.py`.
https://github.com/metomi/rose/blob/19e6c87bf6045950d42e684219ec22ee6656e880/metomi/rosie/graph.py#L22

Digging around I found this discussion: https://github.com/metomi/rose/pull/2366#discussion_r303263303

### PR DESCRIPTION
**Pull request by oliver-sanders**
Closes #2523

* Convert setup file format to setup.cfg.
* Add pygraphviz opt dep.
* Add logic to metomi.rose.rose to provide more helpful error messages
  when optional dependencies are not present.
* Add graphviz to CI deps.

### CODE REVIEW

**Review by MetRonnie — COMMENTED** [review]
Hmm, I get this error (after `pip install -e .[all]`)
```
$ rosie graph
Traceback (most recent call last):
  File "~/.conda/envs/cylc8/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2753, in requires
    deps.extend(dm[safe_extra(ext)])
KeyError: 'graph'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "~/.conda/envs/cylc8/bin/rosie", line 33, in <module>
    sys.exit(load_entry_point('metomi-rose', 'console_scripts', 'rosie')())
  File "~/github/rose/metomi/rose/rose.py", line 220, in rosie
    main(
  File "~/github/rose/metomi/rose/rose.py", line 324, in main
    exec_sub_cmd(ns, sub_cmd, cmd_args)
  File "~/github/rose/metomi/rose/rose.py", line 139, in exec_sub_cmd
    _exec_python(
  File "~/github/rose/metomi/rose/rose.py", line 166, in _exec_python
    fcn = entry_point.load()
  File "~/.conda/envs/cylc8/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2463, in load
    self.require(*args, **kwargs)
  File "~/.conda/envs/cylc8/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2485, in require
    reqs = self.dist.requires(self.extras)
  File "~/.conda/envs/cylc8/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2755, in requires
    raise UnknownExtra(
pkg_resources.UnknownExtra: metomi-rose 2.0b3 has no such extra feature 'graph'
```

**Comment by oliver-sanders** [comment]
Ah, dammit, need to convert the whole thing to setup.cfg

**Review by MetRonnie — APPROVED** [review]
Working now after a `pip install -e .[all]`. Not sure why the tests timing out on GH Actions?

**Comment by oliver-sanders** [comment]
Me neither, giving them a poke.

**Review by wxtim — APPROVED** [review]

**Pull request merged**
