### PR TITLE
rose suite-run --reload: new host, fixed

### LINKED ISSUE #1653: rose suite-run --reload bug with a new task on a new host
If I modify a suite definition to add a new task that will run on a new host (i.e. a host not currently used by this suite) that does not see the same filesystem, ```rose suite-run --reload``` fails with:
```
...
[INFO] install: suite.rc
[FAIL] ssh -oBatchMode=yes oliverh@wrh-1 bash --login -c \'ROSE_VERSION=2015.05.0\ rose\ suite-run\ -v\ -v\ --name=foo\ --run=reload\ --remote=uuid=6123aea0-e53a-4c02-b34c-c452af72aa1f\' # return-code=1, stderr=
[FAIL] [FAIL] [Errno 2] No such file or directory: 'cylc-run/foo'
```

### PR DESCRIPTION
**Pull request by matthewrmshin**
It was previously failing if a new host is added to the suite.

Fix #1653.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
@arjclark @kaday please review.

**Comment by arjclark** [comment]
@kaday - I'll review 1.

**Comment by arjclark** [comment]
Looks good to me. No unexpected problems from the test battery. Over to you @kaday for review 2.

**Comment by kaday** [comment]
test battery t/rose-suite-run/23-reload-host.t fails for me, any ideas @matthewrmshin

**Comment by kaday** [comment]
rsycn'ed the branch and it passes. No unexpected failures. Looks okay to me.

**Pull request merged**
