### PR TITLE
rose demo metadata suite: fix metadata errors

### PR DESCRIPTION
**Pull request by benfitzpatrick**
This fixes metadata-check errors in the `demo/rose-config-edit/demo_meta` suite.

These pop up if you load the suite in `rose edit` and load all apps.

### CODE REVIEW

**Comment by kaday** [comment]
Issue with 06 as discussed.

**Comment by benfitzpatrick** [comment]
Updated.

**Comment by kaday** [comment]
06 is fixed.
Looks good to me.
Passes test battery in my environment.
Over to @matthewrmshin for review2

**Comment by matthewrmshin** [comment]
Looks sane.

**Pull request merged**
