### PR TITLE
rose bush: improve paging and sorting

### LINKED ISSUE #1721: rose bush: display options glob at the view suites for user level
A user has requested a `Display Options` filter as we have for a suite but at the username level to help filter using a glob by for example, suite id, title or project.

### PR DESCRIPTION
**Pull request by matthewrmshin**
Display Options box is now on suites list and cycles list.
Entries per page option for suites list and cycles list.
Suites list can now be filtered by suite names.
Suites list can now be ordered by suite name as well as activity time.

Close #1721.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
@arjclark @kaday please review.

Please note that test numbering is taking into account a single new test (06) in #1785, so we are adding new tests from 07 onwards in this pull request.

**Comment by arjclark** [comment]
Getting the following errors from the test battery:
```
not ok 25 - 00-basic-200-curl-cycles.out
Traceback (most recent call last):
  File "<stdin>", line 25, in <module>
KeyError: "[('offset',), 0]"

...

not ok 27 - 00-basic-200-curl-jobs.out
Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
ValueError: ("[('is_option_on',), None]", False)
```

**Comment by matthewrmshin** [comment]
Test battery should now be OK.

**Comment by arjclark** [comment]
Test battery now passing in my environment. Change looks good to me. Manual testing showing it working.

Over to @kaday

**Comment by matthewrmshin** [comment]
Branch re-based.

**Comment by kaday** [comment]
Looks okay to me. Passes test-battery in my environment. Looks okay in rose bush.

**Pull request merged**
