### PR TITLE
Allow tolerance to be an environment variable

### PR DESCRIPTION
**Pull request by scwhitehouse**
A user has spotted that whilst rose-ana accepts environment variables in filenames, it doesn't for the tolerance. This fixes that issue.

### CODE REVIEW

**Comment by scwhitehouse** [comment]
@stevewardle you should be aware of this - your rose-ana rewrite needs to make sure that environment variables are expanded correctly for all variables.

@matthewrmshin when you get a moment would you mind reviewing? And nominating a second reviewer too?

**Comment by matthewrmshin** [comment]
Looks OK to me. Want to add a test? @stevewardle is probably the best person to review this properly.

**Comment by scwhitehouse** [comment]
Good idea, I've added some tests for this.

**Comment by matthewrmshin** [comment]
Change OK. Test OK.

**Comment by matthewrmshin** [comment]
@stevewardle please review 2.

**Comment by stevewardle** [comment]
Looks fine to me, and I believe we have also had confirmation from the original user that it fixes their problem

**Pull request merged**
