### PR TITLE
Allow ignoring tasks in rose_ana

### LINKED ISSUE #1585: Allow ignoring of tests in rose-ana
It would be nice to be able to switch-off specific tests in an optional configuration (e.g. where runs have different lengths on different platforms). Currently doing [!Name of Test] in an optional configuration gives an error about NoneTypes; this should be fixed - it's probably fairly simple.

### PR DESCRIPTION
**Pull request by scwhitehouse**
An attempt to fix #1585 by checking that a non-None value is return from self.config.get_value().

@matthewrmshin, there might be a better way of doing this, would you mind taking a look and reviewing when you get a minute?

### CODE REVIEW

**Comment by matthewrmshin** [comment]
Change looks OK. Want to add a quick test?

**Comment by scwhitehouse** [comment]
Good idea, test added.

**Comment by matthewrmshin** [comment]
I am getting `not ok 16 - 00-run-basic-ignore-notpresent-1` for some reason.

**Comment by scwhitehouse** [comment]
That seems to intermittently fail; I've deleted that test as it wasn't testing anything which hasn't already been tested. I've also added a sleep command in there to stop those annoying NFS errors when it tries to clean the suite but thinks the files are still in use.

**Pull request merged**
