### PR TITLE
rose_arch: optional target

### PR DESCRIPTION
**Pull request by matthewrmshin**
New syntax to indicate a target may have no source.
New status for target with no source.
doc: optional target and more on rose_arch output.

See also #1707 and #1708.

@arjclark @kaday please review.

### CODE REVIEW

**Comment by arjclark** [comment]
Two possible changes I'd like based on our discussion.

My concern was that if a target was considered optional then it feels that the sources within should be considered optional too. So rather than:
```
[target:(foo)]
sources=(bar)
```
being the way to write this, having [target:(foo)] should imply sources=(bar), so should just be able to write:
```
[target:(foo)]
sources=bar
```
I *think* that this is achievable with minor work by inspecting the `is_target_compulsory` option when setting the `is_source_compulsory` option.

Alternatively, if this would be a major refactor then a note in the documentation (an N.B. directly after your example) saying that for optional targets all sources must be made optional otherwise the task will fail on missing sources would be sufficient.

**Comment by malcolmbrooks** [comment]
Thanks Matt, the syntax as it stands would work for me. Having either optional sources or targets as separate things might be useful in some sitations.

Most archiving, in practice, specifies single sources to a single target. In this case, an optional target is of most use.

**Comment by matthewrmshin** [comment]
Optional target now implies optional sources. Looks like the simple solution works.

**Comment by arjclark** [comment]
Looks good to me. Test battery passing in my environment.

Over to you @kaday

**Comment by kaday** [comment]
Looks okay to me and passes the tests in my environment.

**Pull request merged**
