### PR TITLE
rose bush: jobs: no frill display of cylc-suite.db

### PR DESCRIPTION
**Pull request by matthewrmshin**
Previously, it was failing if it was unable to find `log/job/` in the suite
running directory.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
@arjclark @kaday please review.

**Comment by kaday** [comment]
Test 29 in t/rose-bush/00-basic.t  (00-basic-404-2-curl-jobs.out) fails for me.

**Comment by kaday** [comment]
All tests pass and looks okay to me.

**Comment by arjclark** [comment]
Looks ok to me. No problems from the test battery in my environment.

**Pull request merged**
