### PR TITLE
Remove prune remote logs at from rose prune settings

### PR DESCRIPTION
**Pull request by wxtim**
Closes https://github.com/metomi/rose/issues/2469: Remove `prune-remote-logs-at=cycle` from Rose Prune options.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
I think there are some dangling references to clean up: `git grep prune-remote-logs`

**Comment by wxtim** [comment]
> I think there are some dangling references to clean up: `git grep prune-remote-logs`

Final reference is in a changelog.

**Review by MetRonnie — APPROVED** [review]
Only thing is missing changelog entry (I think there are a number of PRs missing an entry now, could do them all in one go)

**Comment by wxtim** [comment]
> Only thing is missing changelog entry (I think there are a number of PRs missing an entry now, could do them all in one go)

#2521 - I'll do the whole lot at once if that's OK. I think I'm nearly done with the functional changes.

**Comment by wxtim** [comment]
I've misunderstood the issue, which was to remove the rsync, not to remove the option.

**Pull request closed without merging**
