### PR TITLE
Fix selection expanded after change.

### PR DESCRIPTION
**Pull request by oliver-sanders**
The expanded selection was incorrectly updated in the event that the `TreeStore` was modified in a manner which caused a re-ordering of rows which in-turn affected a re-ordering of sections. This is a presentation layer bug as the underlying data-structure is not affected.

#### The steps to reproduce are somewhat convoluted:

1. Open a widget which inherits from the `BaseSummaryDataPanel` class.
    - Note: The data-structure will require at least 4 columns.
    - Note: At least three sections must be present.
2. Group by one column.
3. Expand a section within it ensuring that:
    - The section has 3 or more items.
    - In the section, at least two columns where at least two values are present.
    - The section is not the first in the panel.
4. Sort by **an even number** of columns (at least one of which must contain multiple values).
6. Change a value in one of the remaining columns (multiple values must be present) to the lowest possible value (this way it is certain to change the sorting).

### CODE REVIEW

**Comment by oliver-sanders** [comment]
Test failure fixed by #2123.

**Comment by oliver-sanders** [comment]
@arjclark Can you confirm this resolves the issue you reported?

**Comment by arjclark** [comment]
@oliver-sanders - tested and looks like this keeps the correct group open.

Although the ordering of the groups themselves changes (so if you have two similar groups open you may miss the redraw), this change does address the immediate gotcha of ungrouping things that weren't there previously. I'm not sure how hard/feasible it would be to maintain the ordering of the groupings themselves though?

**Comment by oliver-sanders** [comment]
> I'm not sure how hard/feasible it would be to maintain the ordering of the groupings themselves though?

Short Answer:

Unfortunately sorting is handled internally within GTK. If the re-ordering is an issue the best you can do is to sort by the top level field (in the reported case this would be "packages").

Long Answer:

I had a go at writing a manual iterator to work through the GTK data-structure (gtk.TreeStore via gtk.TreeModel) - one could then manually swap items as desired to effectively define an extra sorting layer. Unfortunately the sorting is handled internally in GTK creating a barrier between the stored and represented data meaning that this approach won't work.

**Comment by arjclark** [comment]
@oliver-sanders - thanks for the clarification. GTK vs. TreeViews/Stores once again proves a nuisance 🙁 

Am happy for this to be the fix to close the reported issue.

**Comment by oliver-sanders** [comment]
I'll wait for #2123 before merging this.

**Comment by oliver-sanders** [comment]
`./t/syntax/00-lib.t` is fixed by #2128

**Pull request merged**
