### PR TITLE
rose_bunch: on failure, print bunch err to stderr

### PR DESCRIPTION
**Pull request by benfitzpatrick**
This is a small change to print out the individual bunch stderr to the job.err on failure so that debugging is easier.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
The test failures are unrelated to this change and will be fixed by #2128 and #2123.

**Comment by benfitzpatrick** [comment]
Great, I did wonder!

**Comment by arjclark** [comment]
@benfitzpatrick - is this going to result in the entire stderr contents from the bunch-<item>.err file getting dumped in the stderr file?

**Comment by benfitzpatrick** [comment]
Yep, just for the ones that failed

**Comment by arjclark** [comment]
> Yep, just for the ones that failed

Not massively ideal then as the sort of things that should be being run through rose bunch should be variants on a command so, for the general case, one fails: all fail. I'm not sure duplicating the entire .stderr file is the way to go - particularly if you consider something like the reconfiguration (original use case) where it chucks out hundreds of lines of warnings to stderr during even a successful run. It may be better to resurrect item 2 of #1876 instead.

**Comment by benfitzpatrick** [comment]
A system's pollution of their output and error is their own problem!

Better to see too much than nothing at all - and this is mainly targeted at users of the cylc gui rather than Rose Bush.

**Comment by arjclark** [comment]
> Better to see too much than nothing at all

So you don't see creation of redundant files as a bad thing to do? No point in having the bunch.err file if you're going to shove it in the job.err.

**Comment by benfitzpatrick** [comment]
Given that neither of us are in the Rose team any more, our opinions are partly moot.

The point of having the bunch.err would be in your situation marked above - drilling down to specifics, particularly if there is a lot of error. Also in your situation above, if the system produces lots of warnings you may want to look at the bunch.err even when the job does not fail. I don't think it's redundant at all.

At the moment everyone does a two-step dance - look at the job.err to see what failed, then look at one of the bunch errors. If they are doing it in the `cylc gui`, they have to load up Rose Bush to get the bunch error. I can actually find out what happened in my failed rose_bunch tasks from the cylc gui! Or in one step on Rose Bush!

**Comment by matthewrmshin** [comment]
🤔

**Comment by benfitzpatrick** [comment]
This is a hard option to name and describe correctly, given that I think this new behaviour should be the default (I reckon everyone wants it except you Andy :p). `disable-combined-stderr-on-failure` (default `false` of course) is the best name I can come up with.

If we can't name it correctly, is it worth having at all? Just pass this in as-is?

**Comment by matthewrmshin** [comment]
Are we going for the old or new behaviour as the default?

**Comment by benfitzpatrick** [comment]
new new new

**Comment by arjclark** [comment]
Discussed offline with @benfitzpatrick and suggested some alternative names for the setting. @benfitzpatrick to follow up with other major users of rose bunch and double check they'd be ok with a change in behaviour.

**Comment by arjclark** [comment]
@benfitzpatrick - does the `extra log files` setting mentioned here: https://github.com/cylc/cylc/pull/2515 make this change redundant?

**Comment by benfitzpatrick** [comment]
No, although it would be more useful if it supported wildcards...

**Comment by arjclark** [comment]
Might it be worth extending the cylc functionality then instead?

**Comment by matthewrmshin** [comment]
Now that it is spring, I think it is time for a spring clean. Please raise a new pull request when we are ready to have another crack at this.

**Pull request closed without merging**
