### PR TITLE
Re-styled the rose documentation with bootstrap 3.

### PR DESCRIPTION
**Pull request by oliver-sanders**
Rose docs now use boostrap 3 default styling.

- ~~html now resides in `html/`~~
- `html/rose-single-page.html` is a single page version which ajax'es in content using the contents section on the home page
- added previous/next buttons to move from one tutorial to the next
- S5/slideshow link is now in the footer ~~(controversial ?)~~ (there is also a link in the navbar)

@matthewrmshin Please Review

### CODE REVIEW

**Comment by oliver-sanders** [comment]
@matthewrmshin Reverted to old directory structure.

**Comment by matthewrmshin** [comment]
Some initial comments:
* Looks good in general.
* Please make sure `t/syntax/01-doc.t` passes.
* I think most of us would probably prefer the S5 link at the top?
* Please add *Single Page Version* link from the top page.
* Restoring from S5 uses the phrase *Single Page* as well. This may cause confusion.
* Please style the *Contents* in each page, i.e. `#content` to not display a dot in front of each `li`.

**Comment by oliver-sanders** [comment]
@matthewrmshin Addressed comments:

- `t/syntax/01` now no longer calls `tidy` from `run-pass` as it will always fail for HTML5 (unrecognised doctype)
- Have added an "S5 Slideshow" link in the navbar
- The homepage now has a "Single Page Version" button
- The "return to single page" button in a S5 Slideshow now has the text "Exit Slideshow"
- Removed bullet points from contents sections

**Comment by matthewrmshin** [comment]
Looking good. The only remaining concern I have is that the single page view is a bit slow. Is it because of the Affix?

@arjclark please review 2. @benfitzpatrick not calling for a review 3, but could you please make sure you are happy with the new style as well?

**Comment by oliver-sanders** [comment]
@matthewrmshin `f5134ea` reduces the lag when scrolling from one section to another in the single page version of the docs.

**Comment by benfitzpatrick** [comment]
Sorry to review 3 and jump the gun on Andy before he has a chance to comment.

I guess it is sort-of-OK to have 3 reviewers being annoying, with such a big change! It is not a like-for-like upgrade.

It looks good in general, but I think the slideshow mode needs more review.

I think it needs to look and act more like the current documentation in slideshow mode:
 * clicking through doesn't work
 * remove the outer margin
 * more left padding around content
 * needs extra indentation around bullet points
 * I like having the top right copyright and version blurb in the slide
 * I also quite like having some colour in the documentation - perhaps we should add a Rose logo or colour the slide counter badge? It stops the user from getting too bored. Even GitHub has some blues and greens.

There will definitely be one or two blips with such a large change. Can the reviewers go through each page and each slide to make sure everything is OK? It is easy to miss things - e.g. Slide 29 in Suites I has extra vertical space.

Can we have a slightly darker grey (or even slightly coloured) background to emphasise the central content in the normal page view? It makes it easier on the eyes.

The single page version has some issues with image size - I don't know how easy that is to fix.

**Comment by arjclark** [comment]
@benfitzpatrick - don't worry I'd already passed on some initial feedback based on running through slideshow mode etc - many of which are issues we had with the old templates at some point or another.

**Comment by arjclark** [comment]
Assigning back to @oliver-sanders while @benfitzpatrick feedback is addressed.

**Comment by oliver-sanders** [comment]
@arjclark @benfitzpatrick Addressed comments, have made the following changes:
- Restored ability to advance slide by clicking in the footer
- Removed outer margin in slideshow mode
- Doubbled the left padding of the presentation slides
- Increased the spacing around bullet points
- Added the rose logo to the title in slideshow mode
- Changed the header in slideshow mode to only show the tutorial name
- Page background now has a subtle shade to make the main content pop out a little
- Changed the "S5 Slideshow" / "Exit Slideshow" button to `btn-primary` for a little extra colour.

**Comment by arjclark** [comment]
In slideshow mode I'm now seeing markup characters in the slide titles, but not for all of them.

e.g. for Suites I, slides 0,2,3 are fine but 1,4,5 have a markup character on the end

**Comment by arjclark** [comment]
In slideshow mode: Suites I, slide 29 - text starts halfway down page...

**Comment by arjclark** [comment]
Spaces still appearing on contents page in titles of some sections

**Comment by arjclark** [comment]
Slide 2 of rose-rug-advanced-tutorials-upgrade-dev.html looks weird.

**Comment by arjclark** [comment]
Font size oddity on slide 17 of rose-rug-advanced-tutorials-macro.html

**Comment by arjclark** [comment]
Slides 18 onwards of rose-rug-advanced-tutorials-trigger.html are also suffering from the misaligned text problem

**Comment by arjclark** [comment]
Some of the slide titles in rose-rug-advanced-tutorials-arch.html look somewhat off.

**Comment by arjclark** [comment]
Slide 18 of rose-rug-advanced-tutorials-suicide.html goes off the bottom of the screen for me. I *think* previously those panels would have fit to page with a scroll bar.

**Comment by arjclark** [comment]
You have a merge issue in rose-configuration.html

**Comment by arjclark** [comment]
Can we have colours back in the table at the end of: rose-configuration-metadata.html

**Comment by arjclark** [comment]
That's all I've got from my latest run through.

**Comment by oliver-sanders** [comment]
@arjclark Addressed issues.

The paragraph symbol visible in the slide selector is a "feature" of S5 Slideshows.

**Comment by arjclark** [comment]
Something odd going on with the slide titles in rose-rug-advanced-tutorials-clock-triggered.html

Based on the other sets of slides the title should be "Clock triggered tasks", am getting:

Clock triggered tasks
Rose Advanced Tutorial: Clock triggered tasks

Can you confirm having tested on the lower resolution monitors in the college to identify any scaling issues that may have been introduced to the slide show?

**Comment by arjclark** [comment]
@oliver-sanders - this branch is in conflict...

**Comment by oliver-sanders** [comment]
@arjclark Addressed a couple more issues.

Testing on lower resolution monitors yielded a couple of minor issues which have a been fixed.

NOTE: I have kept commits separate for ease of reviewing, when we looking ready to merge I can squash these.

**Comment by arjclark** [comment]
@benfitzpatrick - please sanity check ("review 3")

**Comment by benfitzpatrick** [comment]
Font size needs to be bigger in slideshow mode.

`jinja2 templ and installing files and installing files` instead of `jinja2 templating and installing files` in rose-rug-quiz.html. Colour coding of answer statuses in the quiz (was green for correct, red for incorrect).

**Comment by oliver-sanders** [comment]
@benfitzpatrick 
- Changes to slideshow style
  - Increased default font-size by 20%
  - Titles now in bold
  - Lists have slight indent
  - Nested lists have 20% reduction in font-size
- Corrected jinja2 templ... typo
- Added bootstrap labels to quiz to bring back some colour

**Comment by benfitzpatrick** [comment]
(Still has `and installing files and installing files`)

**Comment by benfitzpatrick** [comment]
Other than that, looks good!

**Comment by oliver-sanders** [comment]
@benfitzpatrick Whoops, sorted.

**Pull request merged**
