### PR TITLE
rosie.ws_client_auth: handle keyring denied, disable bad prefixes

### PR DESCRIPTION
**Pull request by benfitzpatrick**
This handles an error thrown by `gnomekeyring` in the rosie auth layer when the keyring is locked.
In current master, a nasty traceback is thrown. The new behaviour is to disable prefixes before use (and notify the user about it) if a `hello` call fails. This applies to other auth failures as well.

The `gnomekeyring` situation can be replicated by launching `seahorse` and locking the `login` keyring. Other auth failures can be replicated by setting the wrong username or password.

@matthewrmshin, please review 1.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
As discussed, it is worth updating the branch with current master, for a better test battery experience.

**Comment by matthewrmshin** [comment]
(Hint: after a merge with master, the new code will not pass the pep8 syntax test.)

**Comment by benfitzpatrick** [comment]
Updated

**Comment by matthewrmshin** [comment]
@arjclark I have pressed the merge button pre-maturely. Could you do a quick sanity check of this change, and if you have any objection, we can fix it in another pull request?

**Comment by arjclark** [comment]
Looks sane enough to me

**Pull request merged**
