### PR TITLE
rose.config: python 3 compatibility

### PR DESCRIPTION
**Pull request by oliver-sanders**
For the most part Rose is a standalone system utility, however, the `rose.config` module is occasionally imported. In order to support the continued use of this ahead of the planned Python3 migration (to follow GUI replacement) the `rose.conf` module and its Rose dependencies have been upgraded to support both Python 2 & 3.

#### Tripwire

Old-style `cmp` functions have now been retired, unfortunately Rose makes heavy use of them for sorting configurations. The sorting algorithm currently used in rose contains branched logic which changes the sorting algorithm based on comparisons of both elements being compared, ...

https://github.com/metomi/rose/blob/ec78ddffc59ae21335e2f33c5431c225f8942215/lib/python/rose/config.py#L1550-L1573

... because of this **the old sorting algorithm cannot be ported to Python 3**.

*Ok, cannot is probably a little strong, perhaps more like should not*

#### Solution?

I've implemented a new-style rich comparison algorithm, this is not a direct replacement for the old sorting system, there are differences in results. I think the new system yields better results but the diffs could potentially cause issues for users (see the diff in t/rose-namelist-dump/02-type.t)?

We will have to take the pain of this one with the Python3 upgrade?.

#### Going Forward

In this branch I've done the bare minimum required for `rose.config` to run under Python 3, hence I have left the old sorting algorithm in-place where it is still used by other parts of rose (e.g. the Rose Edit GUI). Should we:

1) Delay this until we are ready to upgrade the entire codebase into Python 3 and take the pain then.
2) Push ahead with a mixed system (not actually as bad as it sounds?).
3) Upgrade all old style comparisons and take the pain now.

@metomi/core

### CODE REVIEW

**Comment by matthewrmshin** [comment]
Should add Travis CI Python >3.5 tests for this one?

**Comment by oliver-sanders** [comment]
We could but it would require a separate Travis-CI job, this wouldn't be the worst idea as over time the Py3 test component will grow but we would need to somehow split our test battery into a Py2/Py3 component without having to add `if python -c 'import sys; assert(sys.version[0]) == 3'; then skip all` type statements to the head of each test file.

**Comment by sadielbartholomew** [comment]
Forgive me for failing to understand the subtlety here @oliver-sanders, but why can we not just check for Py 3 and if in use define an equivalent ``cmp()`` method, which can be done very easily? Is the crux here that the current *algorithm* making heavy use of it is not very good?

**Comment by oliver-sanders** [comment]
We could, that would be option 4 in the going forward list above but it wouldn't get around the problem and would leave us in the position where rose config produces different results under different python versions.

**Comment by oliver-sanders** [comment]
There might have been a 5th option to implement the rich comparison functions in the `ConfigNode` class. As these comparisons accept two arguments they could emulate the old logic, however, in order to support custom `sort order` we need to be able to provide a sort function at the point where sorting is performed rather than centrally hardcodeing it.

**Comment by sadielbartholomew** [comment]
Thanks for clarifying. I'll have a think about this & see if I any of the outlined options transpires as the better solution in my view.

**Comment by oliver-sanders** [comment]
If we want Python3.7 testing this can be easily done after #2222.

**Comment by oliver-sanders** [comment]
@wxtim Assigning you on this as your work will supersede this PR.

**Comment by matthewrmshin** [comment]
Close as superseded by #2286.

**Pull request closed without merging**
