### PR TITLE
rose.checksum: can now use any hashlib objects

### PR DESCRIPTION
**Pull request by matthewrmshin**
This change allows any hash object in Python's `hashlib` to be used to calculate the check sum of a file. (Only `md5` was allowed before.)

### CODE REVIEW

**Comment by matthewrmshin** [comment]
@benfitzpatrick @arjclark please review.

**Comment by benfitzpatrick** [comment]
Looks fine to me, haven't tested it.

**Comment by arjclark** [comment]
> Looks fine to me, haven't tested it.

@benfitzpatrick - please test before handing on for review 2, I won't be doing anything other than cursory running of the test battery.

**Comment by benfitzpatrick** [comment]
tested

**Comment by arjclark** [comment]
Looks ok to me. Eventually got test battery to pass

**Pull request merged**
