### PR TITLE
rose edit: keyboard shortcuts for multi section summary panel

### LINKED ISSUE #1710: rose edit: keyboard shortcuts for multi-section summary panel
It would be nice to have keyboard shortcuts for common actions in the summary panel
(e.g. `Delete` to delete a section).

### PR DESCRIPTION
**Pull request by oliver-sanders**
closes #1710 

- Added functionality to delete / ignore sections using `Delete` and `Ctrl + I` respectively.
- Enabled multiple selection for BaseSummaryDataPanel

@benfitzpatrick Please Review
@matthewrmshin Please Review

### CODE REVIEW

**Comment by matthewrmshin** [comment]
@oliver-sanders Do you mind squashing the changesets into 1, please?

**Comment by oliver-sanders** [comment]
@matthewrmshin Commits squashed.

**Comment by benfitzpatrick** [comment]
I think this is really good. If we are going for multiple selection, it would be better if possible to adjust the right click menu for multiple-selections so that it is not one-section-specific.

**Comment by oliver-sanders** [comment]
@benfitzpatrick When you click within a gtk.TreeView it destroys the current selection and attempts to create a new one. I can't see any obvious way of overriding this behaviour so I'm unable to prevent gtk from collapsing the selection when you right-click. Would welcome any suggestions to get around this.

**Comment by benfitzpatrick** [comment]
Looks good to me.

**Pull request merged**
