### PR TITLE
rose suite-cmp-vc: new command

### PR DESCRIPTION
**Pull request by matthewrmshin**
To compare VCS information of suite source between latest install and now.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
@dvalters @oliver-sanders please don't forget about this one!

**Comment by dvalters** [comment]
There is traceback if you run the naked command. e.g. `rose suite-cmp-vc`, not a major issue, but would be good if it printed a plain error or redirected to the `--help` option.

**Comment by oliver-sanders** [comment]
```diff
@@ -56,6 +56,8 @@ class SuiteVCComparator(object):
         old_info_file_name = self.suite_engine_proc.get_suite_dir(
             suite_name, 'log', 'rose-suite-run.version')
         old_info = open(old_info_file_name).read().splitlines()
+        if len(old_info) == 1:
+            return False
         handle = StringIO()
         write_source_vc_info(old_info[0], handle, self.popen)
         new_info = handle.getvalue().splitlines()
@@ -88,6 +90,10 @@ def main():
         traceback.print_exc()
         sys.exit(2)
     else:
+        if lines is False:
+            print >> sys.stdout, ('Cannot diff - suite not version controlled '
+                                  'using SVN.')
+            sys.exit(2)
         lines = list(line for line in lines)
         for line in lines:
             event_handler('%s\n' % line, prefix='')
```

**Comment by matthewrmshin** [comment]
@oliver-sanders you win.

**Pull request merged**
