### PR TITLE
Fix #2390 --host=localhost bug

### LINKED ISSUE #2390: "rose suite-run --host=localhost" not working
The "--host" option to rose suite-run seems to work as expected in most cases. However, if you specify "--host=localhost" it gets ignored. The same happens if you specify the name of the localhost.

A workaround is to use "rose suite-run -- --host=locahost".

### PR DESCRIPTION
**Pull request by MetRonnie**
Fix bug preventing use of `--host=localhost` in `rose suite-run`

### CODE REVIEW

**Comment by oliver-sanders** [comment]
Looks sensible, will test shortly.

**Comment by MetRonnie** [comment]
Travis seems to be hanging but this is passing locally (apart from a single failed test to do with a tutorial suite, which happens to be addressed by my earlier PR #2398 )

**Comment by oliver-sanders** [comment]
It looks like the Travis setup has fallen apart for the 2019.01.x branch. It's probably too much of a pain to fix so for now will have to proceed with manual testing.

**Comment by oliver-sanders** [comment]
@wxtim could you give this a quick sanity check / test (ignore Travis)

**Comment by wxtim** [comment]
I'm ready to merge just the instant Ronnie adds himself to `CONTRIBUTING.md`

**Pull request merged**
